=== agh-miss/ResourceMonitor/org.jage.platform-property/src/test/resources/org/jage/property/xml/testHelpers/ageDependency.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="org.jage"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" xmlns="org.jage">

	<xsd:complexType name="component">
		<xsd:sequence>
			<xsd:element name="extends" type="extends" maxOccurs="1" minOccurs="0" />
			<xsd:element name="implements" type="implements" maxOccurs="unbounded" minOccurs="0" />
			<xsd:element name="requires" type="requires" maxOccurs="unbounded" minOccurs="0" />
			<xsd:element name="declaration" type="declaration" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="class" type="xsd:string" use="required" />
		<xsd:attribute name="version" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:element name="component" type="component" />

	<xsd:complexType name="extends">
		<xsd:attribute name="class" type="xsd:string" use="required" />
		<xsd:attribute name="version" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="implements">
		<xsd:attribute name="class" type="xsd:string" use="required" />
		<xsd:attribute name="version" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="requires">
		<xsd:attribute name="class" type="xsd:string" use="required" />
		<xsd:attribute name="version" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="declaration">
		<xsd:sequence>
			<xsd:element name="attribute" type="attribute" maxOccurs="unbounded" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="type">
		<xsd:choice maxOccurs="1" minOccurs="1">
			<xsd:element name="primitive" type="primitive" />
			<xsd:element name="simpleClass" type="simpleClass" />
			<xsd:element name="parameterized" type="parameterized" />
			<xsd:element name="array" type="array" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="parameterized">
		<xsd:choice maxOccurs="2" minOccurs="1">
			<xsd:element name="type" type="type" />
			<xsd:element name="wildcard" type="wildcard" />
		</xsd:choice>
		<xsd:attribute name="class" type="xsd:string" use="required" />
		<xsd:attribute name="interface" type="xsd:boolean" />
		<xsd:attribute name="special">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="list" />
					<xsd:enumeration value="set" />
					<xsd:enumeration value="map" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="array">
		<xsd:sequence>
			<xsd:element name="type" type="type" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="dims" type="xsd:int" use="required" />
	</xsd:complexType>

	<xsd:complexType name="attribute">
		<xsd:sequence>
			<xsd:element name="type" type="type" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="modifier" type="xsd:int" use="optional" />
		<xsd:attribute name="access">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="direct" />
					<xsd:enumeration value="setter" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="required" type="xsd:boolean" />
		<xsd:attribute name="setter" type="xsd:string" />
		<xsd:attribute name="getter" type="xsd:string" />
		<xsd:attribute name="fieldName" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="primitive">
		<xsd:attribute name="name" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="int" />
					<xsd:enumeration value="byte" />
					<xsd:enumeration value="short" />
					<xsd:enumeration value="long" />
					<xsd:enumeration value="float" />
					<xsd:enumeration value="double" />
					<xsd:enumeration value="char" />
					<xsd:enumeration value="boolean" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="wildcard">
		<xsd:choice minOccurs="1" maxOccurs="2">
			<xsd:element name="lower" type="lower" maxOccurs="1" minOccurs="0" />
			<xsd:element name="upper" type="upper" maxOccurs="1" minOccurs="0" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="lower">
		<xsd:sequence>
			<xsd:element name="type" type="type" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="upper">
		<xsd:sequence>
			<xsd:element name="type" type="type" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="simpleClass">
		<xsd:attribute name="class" type="xsd:string" />
		<xsd:attribute name="interface" type="xsd:boolean" />
		<xsd:attribute name="special">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="list" />
					<xsd:enumeration value="set" />
					<xsd:enumeration value="map" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== agh-miss/ResourceMonitor/org.jage.platform-property/src/test/resources/org/jage/property/xml/testHelpers/NoFieldComponent.contract.xml
<?xml version="1.0" encoding="UTF-8"?>
<component
  class="org.jage.property.xml.testHelpers.NoFieldComponent"
  version="1.0.0" xmlns="org.jage"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="org.jage ageDependency.xsd">
  <declaration>
    <attribute access="setter" modifier="2" name="intProperty" required="true">
      <type>
        <primitive name="int"/>
      </type>
    </attribute>
    <attribute access="direct" modifier="2" name="stringProperty" required="true" fieldName="_stringProperty">
      <type>
        <simpleClass class="java.lang.String" interface="false"/>
      </type>
    </attribute>
  </declaration>
</component>

=== agh-miss/ResourceMonitor/org.jage.platform-property/src/test/resources/org/jage/property/xml/testHelpers/AdvancedExampleComponent.contract.xml
<?xml version="1.0" encoding="UTF-8"?>
<component
  class="org.jage.property.xml.testHelpers.AdvancedExampleComponent"
  version="1.0.0" xmlns="org.jage"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="org.jage ageDependency.xsd">
  <extends class="org.jage.property.xml.testHelpers.SimpleExampleComponent"/>
  <declaration>
    <attribute access="setter" modifier="2" name="intProperty" required="true" getter="getIntProperty" setter="setIntProperty">
      <type>
        <primitive name="int"/>
      </type>
    </attribute>
    <attribute access="setter" modifier="2" name="stringProperty" required="true" getter="getStringProperty" setter="setStringProperty">
      <type>
        <simpleClass class="java.lang.String" interface="false"/>
      </type>
    </attribute>
    <attribute access="setter" modifier="2"
      name="changesNotifierProperty2" required="true" getter="getChangesNotifier">
      <type>
        <simpleClass
          class="org.jage.property.testHelpers.ChangesNotifierStub" interface="false"/>
      </type>
    </attribute>
    <attribute access="direct" modifier="2"
      name="changesNotifierProperty" fieldName="_changesNotifierProperty" required="true">
      <type>
        <simpleClass
          class="org.jage.property.testHelpers.ChangesNotifierStub" interface="false"/>
      </type>
    </attribute>
    <attribute access="direct" modifier="2" name="floatProperty" fieldName="_floatProperty" required="true">
      <type>
        <primitive name="float"/>
      </type>
    </attribute>
    <attribute access="direct" modifier="2" name="objectProperty" fieldName="_objectProperty" required="true">
      <type>
        <simpleClass class="java.lang.Object" interface="false"/>
      </type>
    </attribute>
    <attribute access="direct" modifier="2"
      name="monitorableObjectProperty" fieldName="_monitorableObjectProperty" required="true" setter="setMonitorableObjectPropertyValue">
      <type>
        <simpleClass class="java.lang.Object" interface="false"/>
      </type>
    </attribute>
    <attribute access="direct" modifier="2"
      name="monitorableStringProperty" fieldName="_monitorableStringProperty" required="true">
      <type>
        <simpleClass class="java.lang.String" interface="false"/>
      </type>
    </attribute>
    <attribute access="direct" modifier="2"
      name="normalList" fieldName="_normalList" required="true">
      <type>
      	<parameterized class="java.util.List" interface="true" special="list">
      		<type>
        		<simpleClass class="org.jage.property.xml.testHelpers.NormalComponent" interface="false"/>
        	</type>
        </parameterized>
      </type>
    </attribute>
  </declaration>
</component>

=== agh-miss/ResourceMonitor/org.jage.student.examples-solutions/src/main/resources/org/jage/examples/properties/xml/ExampleComponent.contract.xml
<?xml version="1.0" encoding="UTF-8"?>
<component class="org.jage.examples.properties.xml.ExampleComponent" version="1.0.0" xmlns="org.jage"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="org.jage ageDependency.xsd">
	<declaration>
		<attribute access="setter" name="name" required="true" setter="setName" getter="getName">
			<type>
				<simpleClass class="java.lang.String" interface="false" />
			</type>
		</attribute>
		<attribute access="direct" name="version" required="true" fieldName="version">
			<type>
				<primitive name="int" />
			</type>
		</attribute>
		<attribute access="direct" name="holder" required="true" fieldName="holder">
			<type>
				<simpleClass class="java.lang.Object" interface="false" />
			</type>
		</attribute>
	</declaration>
</component>

=== agh-miss/ResourceMonitor/org.jage.student.examples-solutions/src/main/resources/org/jage/examples/properties/xml/SimpleFunctionCounter.contract.xml
<?xml version="1.0" encoding="UTF-8"?>
<component class="org.jage.examples.properties.xml.SimpleFunctionCounter" version="" xmlns="org.jage"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="org.jage ageDependency.xsd">
	<declaration>
		<attribute access="setter" modifier="2" name="xParameter" required="true" setter="setXParameter" getter="getXParameter">
			<type>
				<primitive name="int" />
			</type>
		</attribute>
		<attribute access="direct" modifier="2" name="yParameter" required="true" fieldName="y">
			<type>
				<primitive name="int" />
			</type>
		</attribute>
	</declaration>
</component>

=== agh-miss/ResourceMonitor/org.jage.platform-property/src/test/resources/org/jage/property/xml/testHelpers/SimpleExampleComponent.contract.xml
<?xml version="1.0" encoding="UTF-8"?>
<component
  class="org.jage.property.xml.testHelpers.SimpleExampleComponent"
  version="1.0.0" xmlns="org.jage"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="org.jage ageDependency.xsd">
  <declaration>
    <attribute access="direct" modifier="2" name="complexProperty" fieldName="_complexProperty" required="true">
      <type>
        <simpleClass
          class="org.jage.property.testHelpers.InnerClassWithProperties" interface="false"/>
      </type>
    </attribute>
    <attribute access="direct" modifier="2" name="complexArrayProperty" fieldName="_complexArrayProperty" required="true">
      <type>
        <array dims="1">
          <type>
            <simpleClass
              class="org.jage.property.testHelpers.InnerClassWithProperties" interface="false"/>
          </type>
        </array>
      </type>
    </attribute>
  </declaration>
</component>

=== agh-miss/ResourceMonitor/org.jage.platform-property/src/test/resources/org/jage/property/xml/testHelpers/DifferentNameComponent.contract.xml
<?xml version="1.0" encoding="UTF-8"?>
<component
  class="org.jage.property.xml.testHelpers.AdvancedExampleComponent"
  version="1.0.0" xmlns="org.jage"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="org.jage ageDependency.xsd">
  <extends class="org.jage.property.xml.testHelpers.SimpleExampleComponent"/>
  <declaration>
    <attribute access="setter" modifier="2" name="intProperty" required="true" getter="getIntProperty" setter="setIntProperty">
      <type>
        <primitive name="int"/>
      </type>
    </attribute>
    <attribute access="setter" modifier="2" name="stringProperty" required="true" getter="getStringProperty" setter="setStringProperty">
      <type>
        <simpleClass class="java.lang.String" interface="false"/>
      </type>
    </attribute>
  </declaration>
</component>
